### ISSUE TITLE
npm run build-storybook报错

### ISSUE THREAD

**Issue by hxgqh** [calandnong/uniapp-vue3-storybook-vite-plugin#1]
[vite]: Rollup failed to resolve import "@storybook/window" from "/Users/hxg/codes/github/uniapp-vue3-storybook-vite-plugin/packages/playground/storybook/node_modules/@storybook/addon-interactions/dist/preview.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
Error: [vite]: Rollup failed to resolve import "@storybook/window" from "./node_modules/@storybook/addon-interactions/dist/preview.mjs".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
    at viteWarn (file://./node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:48205:27)
    at onRollupWarning (file://./node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:48237:9)
    at onwarn (file://./node_modules/vite/dist/node/chunks/dep-2b82a1ce.js:47965:13)
    at file://./node_modules/rollup/dist/es/shared/node-entry.js:24276:13
    at Object.logger [as onLog] (file://./node_modules/rollup/dist/es/shared/node-entry.js:25950:9)
    at ModuleLoader.handleInvalidResolvedId (file://./node_modules/rollup/dist/es/shared/node-entry.js:24862:26)
    at file://./node_modules/rollup/dist/es/shared/node-entry.js:24822:26

**Comment by calandnong** [comment]
@hxgqh 你是在在运行的收获遇到这个错误的吗？考虑下删除node_modules，重新使用pnpm install

**Comment by calandnong** [comment]
@hxgqh 切换到dev分支哈

**Comment by hxgqh** [comment]
@calandnong 我的node是 16.20.1. 切换到 dev 分支，出现了不一样的报错：

`
ERR! Error: Cannot find module '/Users/hxg/codes/github/uniapp-vue3-storybook-vite-plugin/packages/playground/storybook/node_modules/unplugin-uniapp-h5/dist/index.cjs'
`

**Comment by hxgqh** [comment]
我依次运行以下命令，产生上面的报错：

```bash
git clone https://github.com/calandnong/uniapp-vue3-storybook-vite-plugin.git
cd uniapp-vue3-storybook-vite-plugin
git checkout dev
pnpm install
cd packages/playground/storybook
npm run build-storybook
```

**Comment by hxgqh** [comment]
npm run storybook模式下没问题，只有build-storybook下才会报错

**Comment by calandnong** [comment]
> npm run storybook模式下没问题，只有build-storybook下才会报错

ok，这个我晚点看看哈，我之前的场景还没考虑build下的使用问题

**Comment by calandnong** [comment]
@hxgqh 此问题已修复哈，可以拉取dev最新代码查看

**Comment by hxgqh** [comment]
@calandnong 太棒了！你这个仓库的打包可以了。

**Comment by hxgqh** [comment]
@calandnong 我这边的仓库，放入组件后，貌似打包还是失败，没有任何报错。可以帮忙看一下吗？https://github.com/haomo-studio/uniapp-storybook
我把您加到这个仓库了。感觉可能是插件里有哪些条件下编译不过去？

**Comment by hxgqh** [comment]
我这个仓库的组件比较多，可能是哪个组件触发了某些 bug

**Comment by hxgqh** [comment]
我的仓库 npm run storybook是可以工作的；npm run build-storybook无法成功。
build 时，插件貌似输出了很多调试日志，很难诊断出来哪里出错了。是否可以考虑将 debug 日志从插件里移除？

**Comment by calandnong** [comment]
> 我的仓库 npm run storybook是可以工作的；npm run build-storybook无法成功。 build 时，插件貌似输出了很多调试日志，很难诊断出来哪里出错了。是否可以考虑将 debug 日志从插件里移除？

已经去除了哈，目前排查了一些问题，我在你的仓库下编译通过了，这边看下是否给个权限，我给你push下，目前还有一个没支持的地方，你在非vue setup模式下renderjs和wxs的多script模式的方式还未支持，这个目前会有一些限制，后面考虑加上

**Comment by hxgqh** [comment]
@calandnong 好的，我给你开一下push权限哈

**Comment by hxgqh** [comment]
你平时在深圳？加个微信，我去拜访一下您啊！我们也在深圳。跟您学习一下！hxgqh1987

**Comment by hxgqh** [comment]
@calandnong 已经添加了push权限了

**Comment by hxgqh** [comment]
可以考虑一下，如果某个story失败，放弃某个story 的编译；成功的 story 仍然可以正常输出

**Comment by calandnong** [comment]
> @calandnong 已经添加了push权限了

bug-fix/fix-storybook-uniapp-plugin-build-mode
push在此分支，最新版插件哈

**Comment by calandnong** [comment]
> 可以考虑一下，如果某个story失败，放弃某个story 的编译；成功的 story 仍然可以正常输出

这个属于storybook的内部的catch了，本插件此处是不感知的哈，如果你需要支持这个能力的话，可以问下@storybook/vue3-vite插件官方是否支持此能力，本插件只是在@storybook/vue3-vite的基础上增加一层较浅层的uniapp语法转换

**Comment by calandnong** [comment]
> hxgqh1987
微信聊，加了，看下build是否符合需求哈，没有问题这个issue先关闭了

**Comment by calandnong** [comment]
这个issue先关闭了哈
