### ISSUE TITLE
自定义修改 UNIAPP_COMPONENTS_PREFIX

### ISSUE THREAD

**Issue by gnmdnd384** [calandnong/uniapp-vue3-storybook-vite-plugin#2]
当前内容
const UNIAPP_COMPONENTS_PREFIX = "uniapp-";

建议可以自定义修改；
https://uniapp.dcloud.net.cn/component/uniui/uni-calendar.html
组件都是 uni-xxx, 比如 uni-button

**Comment by calandnong** [comment]
> 当前内容 const UNIAPP_COMPONENTS_PREFIX = "uniapp-";
> 
> 建议可以自定义修改； https://uniapp.dcloud.net.cn/component/uniui/uni-calendar.html 组件都是 uni-xxx, 比如 uni-button

此处的UNIAPP_COMPONENTS_PREFIX是用于，在源码阶段，进行匹配view/button/video/text等标签，并替换为uniapp的内置组件的h5实现（https://uniapp.dcloud.net.cn/component/view.html#），此处看你给的uniui，这个是扩展组件，非内置组件的实现，或许这里是两个不同的事情？

**Comment by calandnong** [comment]
没有新进度，先关闭issue了哈
