### ISSUE TITLE
不能使用 render 写组件， 这样会渲染不出来

### ISSUE THREAD

**Issue by gnmdnd384** [calandnong/uniapp-vue3-storybook-vite-plugin#3]
// button.stories.ts
const meta: Meta<typeof Comp> = {
  title: 'Button',
  ...commonConfig,
  component: Comp,
  tags: ['autodocs'],
  render: (args) => ({
    components: { Button: Comp  },
    // setup() {
    //   //👇 The args will now be passed down to the template
    //   return { args };
    // },
    template: '<Button v-bind="args"></Button>',
  }),
};
export default meta;

**Comment by gnmdnd384** [comment]
const meta: Meta<typeof Comp> = {
  title: 'Button',
  ...commonConfig,
  component: Comp,
  tags: ['autodocs'],
  render: (args) => ({
    components: { Button: Comp  },
    // setup() {
    //   //👇 The args will now be passed down to the template
    //   return { args };
    // },
    template: '<Button v-bind="args"></Button>',
  }),
};
export default meta;

**Comment by calandnong** [comment]
目前uniapp底层都是使用的vue.runtime.esm.js版本，因为其底层有一些定制的语法，所以不能直接使用vue的官方版本，并且runtime.esm版本是去除了模板解析器的，非完整版本，所以目前不支持这种写法，此处的vue版本来自uniapp官方插件：
插件引用的vue版本h5端实现位置：
https://github.com/calandnong/uniapp-vue3-storybook-vite-plugin/blob/main/packages/unplugin-uniapp-h5/src/libs/uniapp/uni-h5-vue/src/vue.runtime.esm.js
uniapp官方vue的版本h5端实现位置：
https://github.com/dcloudio/uni-app/blob/next/packages/uni-h5-vue/dist/vue.runtime.esm.js

**Comment by calandnong** [comment]
@gnmdnd384 建议换用vue文件的方式走编译的方式哈

**Comment by calandnong** [comment]
没有新进度，先关闭issue了哈
